"""create recurring transactions table

Revision ID: ae8a8c8c44b3
Revises: c729b6565cf2
Create Date: 2026-04-01 16:27:02.540462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ae8a8c8c44b3'
down_revision: Union[str, Sequence[str], None] = 'c729b6565cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('type', postgresql.ENUM('income', 'expense', name='transaction_type', create_type=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', 'yearly', name='recurring_frequency'), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('month_of_year', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('auto_create', sa.Boolean(), nullable=False),
    sa.Column('max_occurrences', sa.Integer(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_recurring_amount_positive'),
    sa.CheckConstraint('day_of_month BETWEEN 1 AND 31 OR day_of_month IS NULL', name='ck_recurring_day_of_month_range'),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6 OR day_of_week IS NULL', name='ck_recurring_day_of_week_range'),
    sa.CheckConstraint('month_of_year BETWEEN 1 AND 12 OR month_of_year IS NULL', name='ck_recurring_month_of_year_range'),
    sa.CheckConstraint('next_due_date >= start_date', name='ck_recurring_next_due_after_start'),
    sa.CheckConstraint('occurrence_count >= 0', name='ck_recurring_occurrence_not_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurring_next_due_active', 'recurring_transactions', ['next_due_date'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_recurring_transactions_id'), 'recurring_transactions', ['id'], unique=False)
    op.create_index('ix_recurring_user_due', 'recurring_transactions', ['user_id', 'next_due_date'], unique=False, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recurring_user_due', table_name='recurring_transactions', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_recurring_transactions_id'), table_name='recurring_transactions')
    op.drop_index('ix_recurring_next_due_active', table_name='recurring_transactions', postgresql_where=sa.text('is_active = true'))
    op.drop_table('recurring_transactions')
    sa.Enum(name='recurring_frequency').drop(op.get_bind())
    # ### end Alembic commands ###
